@echo off
chcp 65001 >nul
cd /d "%~dp0"
echo Installing dependencies...
pip install -r requirements.txt -q
echo Building newspaper...
python build.py
echo Done! Opening page...
start output\index.html
